# Generated by Django 3.2 on 2022-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rctdj', '0002_buses_customer_routes_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buses',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
