# Generated by Django 3.2 on 2022-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rctdj', '0004_auto_20220222_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departure_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
