# Generated by Django 3.2 on 2022-03-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rctdj', '0005_ticket_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cus',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
