# Generated by Django 3.2 on 2022-03-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rctdj', '0007_alter_ticket_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
